#data driven config path
ddconfig_path: "/configs/ddconfigs/chr8.json" 
inference_data_path: "data/chr8-split3.csv"
model_path: "models/sequifier-1882bbb8-best.onnx"
device: "cpu"
seq_length: 50
output_probabilities: True
map_to_id: True
