project_path: .
data_path: PLEASE FILL
read_format: csv
write_format: parquet
selected_columns: [EXAMPLE_INPUT_COLUMN_NAME] # should include all target column, can include additional columns

group_proportions:
- 0.8
- 0.1
- 0.1
seq_length: 48
seq_step_sizes:
- 1
- 1
- 1
max_rows: null
