project_path: .
model_name: default
read_format: parquet
ddconfig_path: PLEASE FILL

selected_columns: [EXAMPLE_INPUT_COLUMN_NAME] # should include all target column, can include additional columns
target_columns: [EXAMPLE_TARGET_COLUMN_NAME]
target_column_types: # 'criterion' in training_spec must also be adapted
  EXAMPLE_TARGET_COLUMN_NAME: real

seq_length: 48
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 128
  d_model_by_column: # the size of the embedding of individual variables, must sum to d_model
    EXAMPLE_INPUT_COLUMN_NAME: # can be left out if either all input variables are real or all are categorical
  nhead: 16
  d_hid: 128
  nlayers: 3
training_spec:
  device: cuda
  epochs: 1000
  iter_save: 10
  batch_size: 100
  log_interval: 10
  lr: 0.0001
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    EXAMPLE_TARGET_COLUMN_NAME: MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: CosineAnnealingLR
    T_max: 111
    eta_min: 0.00001
  continue_training: true
