name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*.*'


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for sphinx-multiversion to fetch tags/branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements-docs.txt
          pip install .

      - name: Build versioned documentation
        run: |
          # The key command: sphinx-multiversion builds docs for all whitelisted tags/branches
          # Output is placed in the 'docs/build/html' directory
          sphinx-multiversion docs/source docs/build/html
      - name: Create CNAME file
        run: echo "sequifier.com" > docs/build/html/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to deploy to GitHub Pages
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
